# Default values for minecraft.
# This is a YAML-formatted file.

namespace: minecraft

image:
  repository: 133610650551.dkr.ecr.us-east-1.amazonaws.com/minecraft-server
  tag: v1.1.8
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ecr-cred

service:
  type: LoadBalancer
  port: 25565

persistence:
  size: 10Gi
  storageClassName: local-path

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1.5Gi

minecraft:
  eula: "TRUE"
  motd: "Welcome to Derek's Minecraft server"
  difficulty: normal
  maxPlayers: 20
  rcon:
    port: 25575
    password: "mcadmin"

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15

exporter:
  enabled: true
  image:
    repository: itzg/mc-monitor
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

networkPolicy:
  enabled: true
