{{- if .Values.exporter.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "minecraft.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
{{- end }}
