apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  ports:
    - name: minecraft
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    {{- if .Values.exporter.enabled }}
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    {{- end }}
