# /Users/derek/Documents/OSU/Spring '26/CS 312/ops-4/k3s/06-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer # k3s ServiceLB will bind port 25565 on the host
  selector:
    app: minecraft
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
