[managed]
ec2 ansible_host=34.238.233.29 ansible_user=ubuntu

[managed:vars]
ansible_ssh_private_key_file=~/.ssh/cs312-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
s3_bucket=ops-3-mc-backups-871de98f
mc_server_motd=Derek Werbowy
