[managed]
ec2 ansible_host=3.84.86.185 ansible_user=ubuntu

[managed:vars]
ansible_ssh_private_key_file=~/.ssh/cs312-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
s3_bucket=ops-3-mc-backups-9fad7488
mc_server_motd=Derek Werbowy
ecr_repository=133610650551.dkr.ecr.us-east-1.amazonaws.com/minecraft-server
